### PR TITLE
Adding missing meta keywords tag for SEO

### PR DESCRIPTION
**Pull request by rodrigograca31**
Not that important for freelancers but still very important nonetheless

### CODE REVIEW

**Comment by rodrigograca31** [comment]
Why are checks failing? It should be ok....
I tough i was missing double quotes but that's not it....

**Comment by rodrigograca31** [comment]
Please try rebuild or something.... It should work....
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by jeromelachaud** [comment]
Thanks for the PR 👍. Haven't setup the travis build properly, no worries 😝.

**Comment by rodrigograca31** [comment]
I lost so much time back and forth trying to make it work.... Other PRs are passing......

**Comment by jeromelachaud** [comment]
Sorry about that 
😟

**Pull request merged**
