### PR TITLE
Use formspree for contact form instead of PHP

### PR DESCRIPTION
**Pull request by enilsen16**
[Formspree.io](http://formspree.io/) sends emails for static sites. This is helpful if you're using a web server that doesn't support PHP. You dont need to register and it is really pain free. 

However to my knowledge Formspree does not support a phone number field.

### CODE REVIEW

**Comment by jeromelachaud** [comment]
Hi Eric, thanks for contributing.

I agree that formspree.io is a handy alternative for non-PHP environment.
I also agree that since this is about generating a static site, PHP should not be mandatory to get the site up and running.

This said, the original PHP form offers more flexibility and some users might want to have full control over their codebase rather than relying on a third-party solution.

So, I think it's best to let the user choose between those two options.

Therefore, I have modified the master branch to include your code and add the option in the config.yaml file.

It rocks, thanks again :wink:

**Comment by enilsen16** [comment]
No problem! I completely agree.

**Comment by enilsen16** [comment]
I just fixed my commits to include instructions for formspree, removed the PHP comments in `contact_static.html` and changed the placeholder to the default formspree email.

**Comment by jeromelachaud** [comment]
:thumbsup:

**Pull request merged**
